name: daddylive-events
on:
  schedule:
    - cron: "0 */7 * * *"
  workflow_dispatch: # Allows manual trigger from the Actions tab

env:
  m_filename: daddylive-events.m3u8
  t_filename: daddylive-events-tivimate.m3u8
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  fetch_m3u8_job:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Manila

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install curl_cffi httpx pytz python-dateutil

      - name: Download and Run Python Script
        run: |
          curl -o daddylive-events.py "${{ secrets.DADDYLIVE_EVENTS_URL }}"
          python daddylive-events.py

      - name: Log the downloaded M3U8 file details
        run: |
          for file in "${{ env.m_filename }}" "${{ env.t_filename }}"; do
            if [ -f "$file" ]; then
              echo "$file downloaded successfully."
              ls -lh "$file"
            else
              echo "Failed to download $file."
            fi
          done

      - name: Commit and push the M3U8 files
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          
          git add "${{ env.m_filename }}" "${{ env.t_filename }}"
          git diff --staged --quiet || git commit -m "Update M3U8 files"
          git push --force
        
