name: topembed-channels
on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch: # Allows manual trigger from the Actions tab

env:
  m_filename: topembed-channels.m3u8
  t_filename: topembed-channels-tivimate.m3u8
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  fetch_m3u8_job:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Manila

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install curl_cffi beautifulsoup4 fuzzywuzzy python-Levenshtein

      - name: Download external Python script
        run: |
          curl -o topembed.py "${{ secrets.TOPEMBED_CHANNELS_URL }}"

      - name: Run the script
        run: python topembed.py

      - name: Log the downloaded M3U8 file details
        run: |
          for file in "${{ env.m_filename }}" "${{ env.t_filename }}"; do
            if [ -f "$file" ]; then
              echo "$file downloaded successfully."
              ls -lh "$file"
            else
              echo "Failed to download $file."
            fi
          done

      - name: Commit and push the M3U8 files
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git diff --staged --quiet || git commit -m "Update epg"
          git push --force
        
